using System;
using System.IO;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
namespace Kedit.Console {
 internal sealed class BackgroundFraming : Window {
  readonly Canvas viewport;readonly FrameworkElement media;readonly MediaElement video;readonly AnimatedTileImage animated;readonly Slider zoom;double naturalWidth,naturalHeight;Point? pointer;bool paused;
  internal PageMedia.Framing Value;
  internal static Rect Layout(double width,double height,double sourceWidth,double sourceHeight,PageMedia.Framing view){double scale=Math.Max(width/sourceWidth,height/sourceHeight)*view.Zoom;double w=sourceWidth*scale,h=sourceHeight*scale;return new Rect(-(w-width)*view.X,-(h-height)*view.Y,w,h);}
  internal BackgroundFraming(Window owner,string file,double aspect,PageMedia.Framing initial){
   Owner=owner;Title="调整背景位置";Width=790;Height=720/aspect+190;WindowStartupLocation=WindowStartupLocation.CenterOwner;ResizeMode=ResizeMode.NoResize;Background=new SolidColorBrush(Color.FromRgb(26,29,36));Value=new PageMedia.Framing{Zoom=initial.Zoom,X=initial.X,Y=initial.Y};
   var panel=new StackPanel{Margin=new Thickness(24)};Content=panel;panel.Children.Add(new TextBlock{Text="拖动画面调整构图 · 滚轮缩放 · 不修改原素材",Foreground=Brushes.White,Margin=new Thickness(0,0,0,14)});viewport=new Canvas{Width=720,Height=720/aspect,ClipToBounds=true,Background=Brushes.Black};panel.Children.Add(viewport);
   if(Path.GetExtension(file).Equals(".mp4",StringComparison.OrdinalIgnoreCase)){video=new MediaElement{Source=new Uri(file),LoadedBehavior=MediaState.Manual,UnloadedBehavior=MediaState.Manual,IsMuted=true,Stretch=Stretch.Fill};media=video;video.MediaOpened+=delegate{naturalWidth=video.NaturalVideoWidth;naturalHeight=video.NaturalVideoHeight;Apply();};video.MediaEnded+=delegate{video.Position=TimeSpan.Zero;if(!paused)video.Play();};video.MediaFailed+=delegate{MessageBox.Show(this,"视频预览无法解码，请检查素材。","预览失败");};Loaded+=delegate{video.Play();};Closed+=delegate{video.Close();};}
   else{var data=TileMedia.Load(File.ReadAllBytes(file));animated=new AnimatedTileImage(data){Stretch=Stretch.Fill};media=animated;naturalWidth=data.Frames[0].PixelWidth;naturalHeight=data.Frames[0].PixelHeight;}
   viewport.Children.Add(media);zoom=new Slider{Minimum=1,Maximum=4,Value=Value.Zoom,Margin=new Thickness(0,14,0,14)};panel.Children.Add(zoom);zoom.ValueChanged+=delegate{Value.Zoom=zoom.Value;Apply();};
   viewport.MouseLeftButtonDown+=delegate(object s,MouseButtonEventArgs e){pointer=e.GetPosition(viewport);viewport.CaptureMouse();};viewport.MouseMove+=delegate(object s,MouseEventArgs e){if(!pointer.HasValue||naturalWidth<=0)return;Point now=e.GetPosition(viewport);var rect=Layout(viewport.Width,viewport.Height,naturalWidth,naturalHeight,Value);if(rect.Width>viewport.Width+.01)Value.X=Math.Max(0,Math.Min(1,Value.X-(now.X-pointer.Value.X)/(rect.Width-viewport.Width)));if(rect.Height>viewport.Height+.01)Value.Y=Math.Max(0,Math.Min(1,Value.Y-(now.Y-pointer.Value.Y)/(rect.Height-viewport.Height)));pointer=now;Apply();};viewport.MouseLeftButtonUp+=delegate{pointer=null;viewport.ReleaseMouseCapture();};viewport.LostMouseCapture+=delegate{pointer=null;};viewport.MouseWheel+=delegate(object s,MouseWheelEventArgs e){zoom.Value=Math.Max(1,Math.Min(4,zoom.Value+(e.Delta>0?.1:-.1)));e.Handled=true;};
   var buttons=new StackPanel{Orientation=Orientation.Horizontal};panel.Children.Add(buttons);Action<string,Action> add=(text,action)=>{var b=new Button{Content=text,Padding=new Thickness(16,8,16,8),Margin=new Thickness(0,0,10,0)};b.Click+=delegate{action();};buttons.Children.Add(b);};add("暂停 / 播放",()=>{paused=!paused;if(video!=null){if(paused)video.Pause();else video.Play();}if(animated!=null)animated.Paused=paused;});add("恢复居中",()=>{Value.X=Value.Y=.5;zoom.Value=1;Apply();});add("保存构图",()=>{if(naturalWidth<=0){MessageBox.Show(this,"素材尚未加载完成。");return;}DialogResult=true;});add("取消",()=>{DialogResult=false;});Apply();
  }
  void Apply(){if(naturalWidth<=0||naturalHeight<=0)return;var r=Layout(viewport.Width,viewport.Height,naturalWidth,naturalHeight,Value);media.Width=r.Width;media.Height=r.Height;Canvas.SetLeft(media,r.X);Canvas.SetTop(media,r.Y);}
 }
 internal sealed partial class DesignPreview {
  readonly Canvas backgroundLayer=new Canvas{ClipToBounds=true,IsHitTestVisible=false};PageMedia.Framing currentFraming=new PageMedia.Framing();
  void ApplyBackgroundFraming(){double w=scene.ActualWidth,h=scene.ActualHeight;double sw=video.NaturalVideoWidth,sh=video.NaturalVideoHeight;var bitmap=gif.Source as BitmapSource;if(gif.Visibility==Visibility.Visible&&bitmap!=null){sw=bitmap.PixelWidth;sh=bitmap.PixelHeight;}if(w<=0||h<=0||sw<=0||sh<=0)return;var rect=BackgroundFraming.Layout(w,h,sw,sh,currentFraming);foreach(FrameworkElement item in new FrameworkElement[]{video,gif}){item.Width=rect.Width;item.Height=rect.Height;Canvas.SetLeft(item,rect.X);Canvas.SetTop(item,rect.Y);}video.Stretch=gif.Stretch=Stretch.Fill;}
  void AdjustBackground(){if(!adminUnlocked)return;if(pageMedia.ProjectDirectory==null){ChooseMediaProject();if(pageMedia.ProjectDirectory==null)return;}try{string path=pageMedia.Resolve(currentMediaPage,mediaFallback);if(!File.Exists(path))throw new IOException("请先为当前页面选择素材。");var dialog=new BackgroundFraming(this,path,scene.ActualWidth/scene.ActualHeight,pageMedia.GetFraming(currentMediaPage));if(dialog.ShowDialog()==true){pageMedia.SetFraming(currentMediaPage,dialog.Value);currentFraming=dialog.Value;ApplyBackgroundFraming();}}catch(Exception ex){MessageBox.Show(this,ex.Message,"构图未保存");}}
  void ShowOther(){home=false;dirty=false;currentMediaPage="other";LoadPageMedia("");title.Text="其他";title.FontSize=23;if(legacyPanel!=null)legacyPanel.Visibility=Visibility.Collapsed;news.Visibility=nav.Visibility=Visibility.Collapsed;settingsToggle.Visibility=Visibility.Visible;panel.Visibility=folded?Visibility.Collapsed:Visibility.Visible;foreach(var tile in tiles)tile.Value.Tag=tile.Key=="其他";form.Children.Clear();formHeader.Children.Clear();formFooter.Children.Clear();formHeader.Children.Add(Text("其他快捷键",24));form.Children.Add(Text("快速打开路径",17));form.Children.Add(Text("通过托盘菜单设置快捷键和要打开的路径。",13,"#ADB9C6"));form.Children.Add(Text("运行 Python 文件",17));form.Children.Add(Text("在资源管理器中选中 Python 文件后触发。快捷键可通过托盘菜单修改。",13,"#ADB9C6"));}
 }
}
