using System;using System.IO;using System.Windows;using System.Windows.Media.Imaging;using System.Windows.Threading;
namespace Kedit.Console {class TileCheck {
 static void Check(bool ok,string message){if(!ok)throw new Exception(message);}
 static byte[] Pixel(BitmapSource image,int x){var normalized=new FormatConvertedBitmap(image,System.Windows.Media.PixelFormats.Bgra32,null,0);var bytes=new byte[4];normalized.CopyPixels(new Int32Rect(x,0,1,1),bytes,4,0);return bytes;}
 static void Pump(int ms){var f=new DispatcherFrame();var t=new DispatcherTimer{Interval=TimeSpan.FromMilliseconds(ms)};t.Tick+=delegate{t.Stop();f.Continue=false;};t.Start();Dispatcher.PushFrame(f);}
 [STAThread] static void Main(string[] args){
 var bytes=File.ReadAllBytes(args[0]);var media=TileMedia.Load(bytes);Check(media.Frames.Count==2,"frame count");Check(media.Delays[0]==80&&media.Delays[1]==160,"frame delay");Check(Pixel(media.Frames[0],0)[2]>200,"red frame");Check(Pixel(media.Frames[1],1)[0]>200,"blue frame");Check(Pixel(media.Frames[1],0)[3]==0,"disposal clears old pixels");
 var crop=TileMedia.Load(bytes,"v1|280|-140|0");Check(crop.Frames[0].PixelWidth==280&&crop.Frames[1].PixelHeight==280,"all frames cropped");Check(TileMedia.Load(bytes).Identity==media.Identity,"same asset identity");
 var app=new Application();var image=new AnimatedTileImage(media);var window=new Window{Width=100,Height=100,Content=image,ShowInTaskbar=false};window.Show();Pump(110);Check(object.ReferenceEquals(image.Source,media.Frames[1]),"animation advances");window.Hide();var paused=image.Source;Pump(220);Check(object.ReferenceEquals(image.Source,paused),"hidden pauses");window.Show();Pump(180);window.WindowState=WindowState.Minimized;paused=image.Source;Pump(220);Check(object.ReferenceEquals(image.Source,paused),"minimize pauses");window.Close();
 var assembly=System.Reflection.Assembly.LoadFrom(args[1]);var shellType=assembly.GetType("Kedit.Console.DesignPreview");var shell=System.Runtime.Serialization.FormatterServices.GetUninitializedObject(shellType);var flags=System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic;
 string project=Path.GetFullPath(Path.Combine(Path.GetDirectoryName(args[0]),"project"));string assets=Path.Combine(project,"Kedit.Console","PreviewAssets");Directory.CreateDirectory(assets);File.WriteAllText(Path.Combine(project,"Kedit.Console","Kedit.Console.csproj"),"<Project/>");
 var page=Activator.CreateInstance(assembly.GetType("Kedit.Console.PageMedia"),new object[]{project});shellType.GetField("pageMedia",flags).SetValue(shell,page);shellType.GetField("adminUnlocked",flags).SetValue(shell,true);
 File.WriteAllBytes(Path.Combine(assets,"kedit.gif"),bytes);File.WriteAllText(Path.Combine(assets,"kedit.gif.crop"),"v1|280|-140|0");var read=shellType.GetMethod("ReadTile",flags);Func<bool,object> resolve=selected=>read.Invoke(shell,new object[]{"Kedit",selected});Func<object,string> identity=value=>(string)value.GetType().GetField("Identity",flags).GetValue(value);
 Check(identity(resolve(false))==identity(resolve(true)),"single source fallback");PreviewCrop.Save(media.Frames[0],Path.Combine(assets,"kedit.selected.png"));Check(identity(resolve(false))!=identity(resolve(true)),"different selected source");File.WriteAllText(Path.Combine(assets,"kedit.selected.share"),"use-unselected");Check(identity(resolve(false))==identity(resolve(true)),"explicit shared source");
 var avatar1=read.Invoke(shell,new object[]{"avatar",false});var avatar2=read.Invoke(shell,new object[]{"avatar",true});Check(identity(avatar1)==identity(avatar2),"avatar is single state");
 System.Console.WriteLine("PASS: GIF disposal, delays, crop, identity, playback, hidden/minimized pause");
 }}}